version: '3.4'





services:
  # zoo:
  #   image: zookeeper:3.4.9
  #   hostname: zoo
  #   ports:
  #     - "2181:2181"
  #   environment:
  #       ZOO_MY_ID: 1
  #       ZOO_PORT: 2181
  #       ZOO_SERVERS: server.1=zoo:2888:3888
  #   volumes:
  #     - ./zk-single-kafka-multiple/zoo/data:/data
  #     - ./zk-single-kafka-multiple/zoo/datalog:/datalog
  # kafka:
  #   image: confluentinc/cp-kafka:5.3.0
  #   hostname: kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
  #     KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
  #   volumes:
  #     - ./zk-single-kafka-multiple/kafka1/data:/var/lib/kafka/data
  #   depends_on:
  #     - zoo
  # manager:
  #   image: sheepkiller/kafka-manager
  #   ports:
  #     - 9000:9000
  #   environment:
  #     - ZK_HOSTS=zoo:2181
  #   depends_on:
  #     - zoo
  # seq:
    # image: datalust/seq:latest
    # environment:
    #   - ACCEPT_EULA=Y
    # ports:
    #   - "5341:80"

   
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    environment:
        POSTGRES_USER: kong
        POSTGRES_DB: kong
        POSTGRES_PASSWORD: kong
    ports:
        - "1000:5432"
    volumes:
        - /root/docker-compose/kong/db-data:/var/lib/postgresql/data
    networks:
        - kong-net 
    
  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    restart: on-failure
    depends_on:
        - kong-database
    links:
        - kong-database:kong-database
    environment:
        KONG_DATABASE: postgres
        KONG_PG_HOST: kong-database
        KONG_PG_USER: kong
        KONG_PG_PASSWORD: kong
        KONG_CASSANDRA_CONTACT_POINTS: kong-database
    entrypoint: sh -c "sleep 100 && kong migrations bootstrap --vv"
    networks:
        - kong-net
            
  kong:
    image: kong:latest
    container_name: kong
    restart: on-failure
    links:
        - kong-database:kong-database
    networks:
        - kong-net
    environment:
        KONG_DATABASE: postgres
        KONG_PG_HOST: kong-database
        KONG_PG_USER: kong
        KONG_PG_PASSWORD: kong
        KONG_CASSANDRA_CONTACT_POINTS: kong-database
        KONG_PROXY_ACCESS_LOG: /dev/stdout
        KONG_ADMIN_ACCESS_LOG: /dev/stdout
        KONG_PROXY_ERROR_LOG: /dev/stderr
        KONG_ADMIN_ERROR_LOG: /dev/stderr
        KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
        - "1001:8000"
        - "1002:8443"
        - "1003:8001"
        - "1004:8444"
    
  konga-prepare:
      image: pantsel/konga
      container_name: konga-prepare
      command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga"
      networks:
          - kong-net
      restart: on-failure
      links:
          - kong-database:kong-database
      depends_on:
          - kong-database
  
  konga:
      image: pantsel/konga
      container_name: konga
      restart: on-failure
      links:
          - kong-database:kong-database
      depends_on:
          - kong-database
      networks:
          - kong-net
      environment:
          DB_ADAPTER: postgres
          DB_HOST: kong-database
          DB_PORT: 5432
          DB_USER: kong
          DB_PASSWORD: kong
          DB_DATABASE: konga
          KONGA_HOOK_TIMEOUT: 120000
          NODE_ENV: production  
      ports:
          - "1005:1337"

networks:
    kong-net:
        name: kong-net
        driver: bridge
        
